services:
  - type: web
    name: jeremie-soccer-2026
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost
      - key: CORS_ALLOWED_ORIGINS
        value: https://jeremie-soccer-2026.vercel.app